//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssBandit.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RssBandit.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_feedsources_32 {
            get {
                object obj = ResourceManager.GetObject("add_feedsources_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_folder_32 {
            get {
                object obj = ResourceManager.GetObject("add_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_newsserver_16 {
            get {
                object obj = ResourceManager.GetObject("add_newsserver_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_user_16 {
            get {
                object obj = ResourceManager.GetObject("add_user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AniImagesXP {
            get {
                object obj = ResourceManager.GetObject("AniImagesXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppBusy {
            get {
                object obj = ResourceManager.GetObject("AppBusy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppBusyXP {
            get {
                object obj = ResourceManager.GetObject("AppBusyXP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppTray {
            get {
                object obj = ResourceManager.GetObject("AppTray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppTrayXP {
            get {
                object obj = ResourceManager.GetObject("AppTrayXP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arrows_Left_16 {
            get {
                object obj = ResourceManager.GetObject("Arrows_Left_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Comment_16 {
            get {
                object obj = ResourceManager.GetObject("Comment_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Connected {
            get {
                object obj = ResourceManager.GetObject("Connected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_32 {
            get {
                object obj = ResourceManager.GetObject("delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Disconnected {
            get {
                object obj = ResourceManager.GetObject("Disconnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_preferences_16 {
            get {
                object obj = ResourceManager.GetObject("document_preferences_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_preferences_32 {
            get {
                object obj = ResourceManager.GetObject("document_preferences_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_location_16 {
            get {
                object obj = ResourceManager.GetObject("earth_location_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_location_24 {
            get {
                object obj = ResourceManager.GetObject("earth_location_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_location_32 {
            get {
                object obj = ResourceManager.GetObject("earth_location_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envelope_closed_32 {
            get {
                object obj = ResourceManager.GetObject("envelope_closed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envelope_open_32 {
            get {
                object obj = ResourceManager.GetObject("envelope_open_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envelope_open_flag_32 {
            get {
                object obj = ResourceManager.GetObject("envelope_open_flag_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envelope_open_reply_16 {
            get {
                object obj = ResourceManager.GetObject("envelope_open_reply_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap envelope_open_reply_32 {
            get {
                object obj = ResourceManager.GetObject("envelope_open_reply_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facebook {
            get {
                object obj = ResourceManager.GetObject("facebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed_discovered_16 {
            get {
                object obj = ResourceManager.GetObject("feed_discovered_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed_discovered_32 {
            get {
                object obj = ResourceManager.GetObject("feed_discovered_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed_doc {
            get {
                object obj = ResourceManager.GetObject("feed_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon feedRefresh {
            get {
                object obj = ResourceManager.GetObject("feedRefresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_blue_16 {
            get {
                object obj = ResourceManager.GetObject("flag_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_clear_16 {
            get {
                object obj = ResourceManager.GetObject("flag_clear_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_complete_16 {
            get {
                object obj = ResourceManager.GetObject("flag_complete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_green_16 {
            get {
                object obj = ResourceManager.GetObject("flag_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_orange_16 {
            get {
                object obj = ResourceManager.GetObject("flag_orange_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_purple_16 {
            get {
                object obj = ResourceManager.GetObject("flag_purple_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_red_16 {
            get {
                object obj = ResourceManager.GetObject("flag_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_yellow_16 {
            get {
                object obj = ResourceManager.GetObject("flag_yellow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_16 {
            get {
                object obj = ResourceManager.GetObject("funnel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Go_32 {
            get {
                object obj = ResourceManager.GetObject("Go_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap google {
            get {
                object obj = ResourceManager.GetObject("google", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_Icon_16 {
            get {
                object obj = ResourceManager.GetObject("Help_Icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hotnews_16 {
            get {
                object obj = ResourceManager.GetObject("hotnews_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Html_16 {
            get {
                object obj = ResourceManager.GetObject("Html_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Html_32 {
            get {
                object obj = ResourceManager.GetObject("Html_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manage_identities {
            get {
                object obj = ResourceManager.GetObject("manage_identities", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mark_feed_read_16 {
            get {
                object obj = ResourceManager.GetObject("mark_feed_read_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minus_16 {
            get {
                object obj = ResourceManager.GetObject("Minus_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_2_folder_16 {
            get {
                object obj = ResourceManager.GetObject("move_2_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move_2_folder_32 {
            get {
                object obj = ResourceManager.GetObject("move_2_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New_Certificate_16 {
            get {
                object obj = ResourceManager.GetObject("New_Certificate_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_doc_feed_32 {
            get {
                object obj = ResourceManager.GetObject("new_doc_feed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_doc_feed_search_32 {
            get {
                object obj = ResourceManager.GetObject("new_doc_feed_search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_doc_nntp_32 {
            get {
                object obj = ResourceManager.GetObject("new_doc_nntp_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newsgator {
            get {
                object obj = ResourceManager.GetObject("newsgator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newsgroups {
            get {
                object obj = ResourceManager.GetObject("newsgroups", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next_unread_feed_16 {
            get {
                object obj = ResourceManager.GetObject("next_unread_feed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next_unread_item_16 {
            get {
                object obj = ResourceManager.GetObject("next_unread_item_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nntp_doc {
            get {
                object obj = ResourceManager.GetObject("nntp_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nntp_doc_16 {
            get {
                object obj = ResourceManager.GetObject("nntp_doc_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap no_feed_discovered_16 {
            get {
                object obj = ResourceManager.GetObject("no_feed_discovered_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap no_feed_discovered_32 {
            get {
                object obj = ResourceManager.GetObject("no_feed_discovered_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Plus_16 {
            get {
                object obj = ResourceManager.GetObject("Plus_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap podcasts {
            get {
                object obj = ResourceManager.GetObject("podcasts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap post_item {
            get {
                object obj = ResourceManager.GetObject("post_item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap properties {
            get {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_all_feedsources_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_all_feedsources_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_feed_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_feed_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_folder_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename_16 {
            get {
                object obj = ResourceManager.GetObject("rename_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rssbandit_16 {
            get {
                object obj = ResourceManager.GetObject("rssbandit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rssbandit_32 {
            get {
                object obj = ResourceManager.GetObject("rssbandit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon RssDiscovered0 {
            get {
                object obj = ResourceManager.GetObject("RssDiscovered0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon RssDiscovered1 {
            get {
                object obj = ResourceManager.GetObject("RssDiscovered1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rules {
            get {
                object obj = ResourceManager.GetObject("rules", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_folder_16 {
            get {
                object obj = ResourceManager.GetObject("search_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_folder_32 {
            get {
                object obj = ResourceManager.GetObject("search_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selection {
            get {
                object obj = ResourceManager.GetObject("selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subscribe_feedsources_32 {
            get {
                object obj = ResourceManager.GetObject("subscribe_feedsources_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subscriptions_folder_16 {
            get {
                object obj = ResourceManager.GetObject("subscriptions_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subscriptions_folder_32 {
            get {
                object obj = ResourceManager.GetObject("subscriptions_folder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unread {
            get {
                object obj = ResourceManager.GetObject("unread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unread_envelope {
            get {
                object obj = ResourceManager.GetObject("unread_envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon UnreadFeedItems {
            get {
                object obj = ResourceManager.GetObject("UnreadFeedItems", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon UnreadFeedItemsXP {
            get {
                object obj = ResourceManager.GetObject("UnreadFeedItemsXP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_Certificate_16 {
            get {
                object obj = ResourceManager.GetObject("View_Certificate_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap watch_icon {
            get {
                object obj = ResourceManager.GetObject("watch_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webpage_icon {
            get {
                object obj = ResourceManager.GetObject("webpage_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
