#region Copyright
/*
 * Copyright (c) 2007 by Dare Obasanjo 
 * Based on code found at http://www.codeproject.com/cs/miscctrl/csEXWB.asp?msg=2134983 
 */   
#endregion 

namespace IEControl 
{
	/// <summary>
	/// Summary description for HTMLDispIDs.
	/// </summary>
	internal static class HTMLDispIDs 
	{

		//    DISPIDs for event set HTMLWindowEvents2
		public const int DISPID_XOBJ_MAX = -2147352577;
		public const int DISPID_XOBJ_BASE = DISPID_XOBJ_MIN;
		public const int STDDISPID_XOBJ_ONBLUR = (DISPID_XOBJ_BASE);
		public const int STDDISPID_XOBJ_ONFOCUS = (DISPID_XOBJ_BASE + 1);
		public const int STDDISPID_XOBJ_BEFOREUPDATE = (DISPID_XOBJ_BASE + 4);
		public const int STDDISPID_XOBJ_AFTERUPDATE = (DISPID_XOBJ_BASE + 5);
		public const int STDDISPID_XOBJ_ONROWEXIT = (DISPID_XOBJ_BASE + 6);
		public const int STDDISPID_XOBJ_ONROWENTER = (DISPID_XOBJ_BASE + 7);
		public const int STDDISPID_XOBJ_ONMOUSEOVER = (DISPID_XOBJ_BASE + 8);
		public const int STDDISPID_XOBJ_ONMOUSEOUT = (DISPID_XOBJ_BASE + 9);
		public const int STDDISPID_XOBJ_ONHELP = (DISPID_XOBJ_BASE + 10);
		public const int STDDISPID_XOBJ_ONDRAGSTART = (DISPID_XOBJ_BASE + 11);
		public const int STDDISPID_XOBJ_ONSELECTSTART = (DISPID_XOBJ_BASE + 12);
		public const int STDDISPID_XOBJ_ERRORUPDATE = (DISPID_XOBJ_BASE + 13);
		public const int STDDISPID_XOBJ_ONDATASETCHANGED = (DISPID_XOBJ_BASE + 14);
		public const int STDDISPID_XOBJ_ONDATAAVAILABLE = (DISPID_XOBJ_BASE + 15);
		public const int STDDISPID_XOBJ_ONDATASETCOMPLETE = (DISPID_XOBJ_BASE + 16);
		public const int STDDISPID_XOBJ_ONFILTER = (DISPID_XOBJ_BASE + 17);
		public const int STDDISPID_XOBJ_ONLOSECAPTURE = (DISPID_XOBJ_BASE + 18);
		public const int STDDISPID_XOBJ_ONPROPERTYCHANGE = (DISPID_XOBJ_BASE + 19);
		public const int STDDISPID_XOBJ_ONDRAG = (DISPID_XOBJ_BASE + 20);
		public const int STDDISPID_XOBJ_ONDRAGEND = (DISPID_XOBJ_BASE + 21);
		public const int STDDISPID_XOBJ_ONDRAGENTER = (DISPID_XOBJ_BASE + 22);
		public const int STDDISPID_XOBJ_ONDRAGOVER = (DISPID_XOBJ_BASE + 23);
		public const int STDDISPID_XOBJ_ONDRAGLEAVE = (DISPID_XOBJ_BASE + 24);
		public const int STDDISPID_XOBJ_ONDROP = (DISPID_XOBJ_BASE + 25);
		public const int STDDISPID_XOBJ_ONCUT = (DISPID_XOBJ_BASE + 26);
		public const int STDDISPID_XOBJ_ONCOPY = (DISPID_XOBJ_BASE + 27);
		public const int STDDISPID_XOBJ_ONPASTE = (DISPID_XOBJ_BASE + 28);
		public const int STDDISPID_XOBJ_ONBEFORECUT = (DISPID_XOBJ_BASE + 29);
		public const int STDDISPID_XOBJ_ONBEFORECOPY = (DISPID_XOBJ_BASE + 30);
		public const int STDDISPID_XOBJ_ONBEFOREPASTE = (DISPID_XOBJ_BASE + 31);
		public const int STDDISPID_XOBJ_ONROWSDELETE = (DISPID_XOBJ_BASE + 32);
		public const int STDDISPID_XOBJ_ONROWSINSERTED = (DISPID_XOBJ_BASE + 33);
		public const int STDDISPID_XOBJ_ONCELLCHANGE = (DISPID_XOBJ_BASE + 34);
		public const int STDPROPID_XOBJ_DISABLED = (DISPID_XOBJ_BASE + 0x4C); //+76

		public const int DISPID_AMBIENT_DLCONTROL = -5512;

		public const int DISPID_NORMAL_FIRST = 1000;

		public const int DISPID_ONABORT = (DISPID_NORMAL_FIRST);
		public const int DISPID_ONCHANGE = (DISPID_NORMAL_FIRST + 1);
		public const int DISPID_ONERROR = (DISPID_NORMAL_FIRST + 2);
		public const int DISPID_ONLOAD = (DISPID_NORMAL_FIRST + 3);
		public const int DISPID_ONSELECT = (DISPID_NORMAL_FIRST + 6);
		public const int DISPID_ONSUBMIT = (DISPID_NORMAL_FIRST + 7);
		public const int DISPID_ONUNLOAD = (DISPID_NORMAL_FIRST + 8);
		public const int DISPID_ONBOUNCE = (DISPID_NORMAL_FIRST + 9);
		public const int DISPID_ONFINISH = (DISPID_NORMAL_FIRST + 10);
		public const int DISPID_ONSTART = (DISPID_NORMAL_FIRST + 11);
		public const int DISPID_ONLAYOUT = (DISPID_NORMAL_FIRST + 13);
		public const int DISPID_ONSCROLL = (DISPID_NORMAL_FIRST + 14);
		public const int DISPID_ONRESET = (DISPID_NORMAL_FIRST + 15);
		public const int DISPID_ONRESIZE = (DISPID_NORMAL_FIRST + 16);
		public const int DISPID_ONBEFOREUNLOAD = (DISPID_NORMAL_FIRST + 17);
		public const int DISPID_ONCHANGEFOCUS = (DISPID_NORMAL_FIRST + 18);
		public const int DISPID_ONCHANGEBLUR = (DISPID_NORMAL_FIRST + 19);
		public const int DISPID_ONPERSIST = (DISPID_NORMAL_FIRST + 20);
		public const int DISPID_ONPERSISTSAVE = (DISPID_NORMAL_FIRST + 21);
		public const int DISPID_ONPERSISTLOAD = (DISPID_NORMAL_FIRST + 22);
		public const int DISPID_ONCONTEXTMENU = (DISPID_NORMAL_FIRST + 23);
		public const int DISPID_ONBEFOREPRINT = (DISPID_NORMAL_FIRST + 24);
		public const int DISPID_ONAFTERPRINT = (DISPID_NORMAL_FIRST + 25);
		public const int DISPID_ONSTOP = (DISPID_NORMAL_FIRST + 26);
		public const int DISPID_ONBEFOREEDITFOCUS = (DISPID_NORMAL_FIRST + 27);
		public const int DISPID_ONMOUSEHOVER = (DISPID_NORMAL_FIRST + 28);
		public const int DISPID_ONCONTENTREADY = (DISPID_NORMAL_FIRST + 29);
		public const int DISPID_ONLAYOUTCOMPLETE = (DISPID_NORMAL_FIRST + 30);
		public const int DISPID_ONPAGE = (DISPID_NORMAL_FIRST + 31);
		public const int DISPID_ONLINKEDOVERFLOW = (DISPID_NORMAL_FIRST + 32);
		public const int DISPID_ONMOUSEWHEEL = (DISPID_NORMAL_FIRST + 33);
		public const int DISPID_ONBEFOREDEACTIVATE = (DISPID_NORMAL_FIRST + 34);
		public const int DISPID_ONMOVE = (DISPID_NORMAL_FIRST + 35);
		public const int DISPID_ONCONTROLSELECT = (DISPID_NORMAL_FIRST + 36);
		public const int DISPID_ONSELECTIONCHANGE = (DISPID_NORMAL_FIRST + 37);
		public const int DISPID_ONMOVESTART = (DISPID_NORMAL_FIRST + 38);
		public const int DISPID_ONMOVEEND = (DISPID_NORMAL_FIRST + 39);
		public const int DISPID_ONRESIZESTART = (DISPID_NORMAL_FIRST + 40);
		public const int DISPID_ONRESIZEEND = (DISPID_NORMAL_FIRST + 41);
		public const int DISPID_ONMOUSEENTER = (DISPID_NORMAL_FIRST + 42);
		public const int DISPID_ONMOUSELEAVE = (DISPID_NORMAL_FIRST + 43);
		public const int DISPID_ONACTIVATE = (DISPID_NORMAL_FIRST + 44);
		public const int DISPID_ONDEACTIVATE = (DISPID_NORMAL_FIRST + 45);
		public const int DISPID_ONMULTILAYOUTCLEANUP = (DISPID_NORMAL_FIRST + 46);
		public const int DISPID_ONBEFOREACTIVATE = (DISPID_NORMAL_FIRST + 47);
		public const int DISPID_ONFOCUSIN = (DISPID_NORMAL_FIRST + 48);
		public const int DISPID_ONFOCUSOUT = (DISPID_NORMAL_FIRST + 49);

		public const int DISPID_EVPROP_ONFINISH = (DISPID_EVENTS + 26);
		public const int DISPID_EVMETH_ONFINISH = DISPID_ONFINISH;
		public const int DISPID_EVPROP_ONSTART = (DISPID_EVENTS + 27);
		public const int DISPID_EVMETH_ONSTART = DISPID_ONSTART;
		public const int DISPID_EVPROP_ONABORT = (DISPID_EVENTS + 28);
		public const int DISPID_EVMETH_ONABORT = DISPID_ONABORT;
		public const int DISPID_EVPROP_ONERROR = (DISPID_EVENTS + 29);
		public const int DISPID_EVMETH_ONERROR = DISPID_ONERROR;
		public const int DISPID_EVPROP_ONCHANGE = (DISPID_EVENTS + 30);
		public const int DISPID_EVMETH_ONCHANGE = DISPID_ONCHANGE;
		public const int DISPID_EVPROP_ONSCROLL = (DISPID_EVENTS + 31);
		public const int DISPID_EVMETH_ONSCROLL = DISPID_ONSCROLL;
		public const int DISPID_EVPROP_ONLOAD = (DISPID_EVENTS + 32);
		public const int DISPID_EVMETH_ONLOAD = DISPID_ONLOAD;
		public const int DISPID_EVPROP_ONUNLOAD = (DISPID_EVENTS + 33);
		public const int DISPID_EVMETH_ONUNLOAD = DISPID_ONUNLOAD;
		public const int DISPID_EVPROP_ONLAYOUT = (DISPID_EVENTS + 34);
		public const int DISPID_EVMETH_ONLAYOUT = DISPID_ONLAYOUT;
		public const int DISPID_EVPROP_ONDRAGSTART = (DISPID_EVENTS + 35);
		public const int DISPID_EVMETH_ONDRAGSTART = STDDISPID_XOBJ_ONDRAGSTART;
		public const int DISPID_EVPROP_ONRESIZE = (DISPID_EVENTS + 36);
		public const int DISPID_EVMETH_ONRESIZE = DISPID_ONRESIZE;
		public const int DISPID_EVPROP_ONSELECTSTART = (DISPID_EVENTS + 37);
		public const int DISPID_EVMETH_ONSELECTSTART = STDDISPID_XOBJ_ONSELECTSTART;
		public const int DISPID_EVPROP_ONERRORUPDATE = (DISPID_EVENTS + 38);
		public const int DISPID_EVMETH_ONERRORUPDATE = STDDISPID_XOBJ_ERRORUPDATE;
		public const int DISPID_EVPROP_ONBEFOREUNLOAD = (DISPID_EVENTS + 39);
		public const int DISPID_EVMETH_ONBEFOREUNLOAD = DISPID_ONBEFOREUNLOAD;
		public const int DISPID_EVPROP_ONBEFOREPRINT = (DISPID_EVENTS + 66);
		public const int DISPID_EVMETH_ONBEFOREPRINT = DISPID_ONBEFOREPRINT;
		public const int DISPID_EVPROP_ONAFTERPRINT = (DISPID_EVENTS + 67);
		public const int DISPID_EVMETH_ONAFTERPRINT = DISPID_ONAFTERPRINT;
		public const int DISPID_EVPROP_ONHELP = (DISPID_EVENTS + 13);
		public const int DISPID_EVMETH_ONHELP = STDDISPID_XOBJ_ONHELP;
		public const int DISPID_EVPROP_ONFOCUS = (DISPID_EVENTS + 14);
		public const int DISPID_EVMETH_ONFOCUS = STDDISPID_XOBJ_ONFOCUS;
		public const int DISPID_EVPROP_ONBLUR = (DISPID_EVENTS + 15);
		public const int DISPID_EVMETH_ONBLUR = STDDISPID_XOBJ_ONBLUR;
		public const int DISPID_HTMLWINDOWEVENTS2_ONLOAD = DISPID_EVMETH_ONLOAD;
		public const int DISPID_HTMLWINDOWEVENTS2_ONUNLOAD = DISPID_EVMETH_ONUNLOAD;
		public const int DISPID_HTMLWINDOWEVENTS2_ONHELP = DISPID_EVMETH_ONHELP;
		public const int DISPID_HTMLWINDOWEVENTS2_ONFOCUS = DISPID_EVMETH_ONFOCUS;
		public const int DISPID_HTMLWINDOWEVENTS2_ONBLUR = DISPID_EVMETH_ONBLUR;
		public const int DISPID_HTMLWINDOWEVENTS2_ONERROR = DISPID_EVMETH_ONERROR;
		public const int DISPID_HTMLWINDOWEVENTS2_ONRESIZE = DISPID_EVMETH_ONRESIZE;
		public const int DISPID_HTMLWINDOWEVENTS2_ONSCROLL = DISPID_EVMETH_ONSCROLL;
		public const int DISPID_HTMLWINDOWEVENTS2_ONBEFOREUNLOAD = DISPID_EVMETH_ONBEFOREUNLOAD;
		public const int DISPID_HTMLWINDOWEVENTS2_ONBEFOREPRINT = DISPID_EVMETH_ONBEFOREPRINT;
		public const int DISPID_HTMLWINDOWEVENTS2_ONAFTERPRINT = DISPID_EVMETH_ONAFTERPRINT;


		//    DISPIDs for interface IHTMLFramesCollection2

		public const int DISPID_IHTMLFRAMESCOLLECTION2_ITEM = 0;
		public const int DISPID_IHTMLFRAMESCOLLECTION2_LENGTH = 1001;

		public const int DISPID_XOBJ_MIN = -2147418112;
		public const int DISPID_EVENTS = (DISPID_XOBJ_MIN + 6000);

		// DISPIDs for interface IHTMLWindow2

		public const int DISPID_IHTMLWINDOW2_FRAMES = 1100;
		public const int DISPID_IHTMLWINDOW2_DEFAULTSTATUS = 1101;
		public const int DISPID_IHTMLWINDOW2_STATUS = 1102;
		public const int DISPID_IHTMLWINDOW2_SETTIMEOUT = 1172;
		public const int DISPID_IHTMLWINDOW2_CLEARTIMEOUT = 1104;
		public const int DISPID_IHTMLWINDOW2_ALERT = 1105;
		public const int DISPID_IHTMLWINDOW2_CONFIRM = 1110;
		public const int DISPID_IHTMLWINDOW2_PROMPT = 1111;
		public const int DISPID_IHTMLWINDOW2_IMAGE = 1125;
		public const int DISPID_IHTMLWINDOW2_LOCATION = 14;
		public const int DISPID_IHTMLWINDOW2_HISTORY = 2;
		public const int DISPID_IHTMLWINDOW2_CLOSE = 3;
		public const int DISPID_IHTMLWINDOW2_OPENER = 4;
		public const int DISPID_IHTMLWINDOW2_NAVIGATOR = 5;
		public const int DISPID_IHTMLWINDOW2_NAME = 11;
		public const int DISPID_IHTMLWINDOW2_PARENT = 12;
		public const int DISPID_IHTMLWINDOW2_OPEN = 13;
		public const int DISPID_IHTMLWINDOW2_SELF = 20;
		public const int DISPID_IHTMLWINDOW2_TOP = 21;
		public const int DISPID_IHTMLWINDOW2_WINDOW = 22;
		public const int DISPID_IHTMLWINDOW2_NAVIGATE = 25;		
		
            
		public const int DISPID_IHTMLWINDOW2_ONFOCUS = DISPID_EVPROP_ONFOCUS;
		public const int DISPID_IHTMLWINDOW2_ONBLUR = DISPID_EVPROP_ONBLUR;
		public const int DISPID_IHTMLWINDOW2_ONLOAD = DISPID_EVPROP_ONLOAD;
		public const int DISPID_IHTMLWINDOW2_ONBEFOREUNLOAD = DISPID_EVPROP_ONBEFOREUNLOAD;
		public const int DISPID_IHTMLWINDOW2_ONUNLOAD = DISPID_EVPROP_ONUNLOAD;
		public const int DISPID_IHTMLWINDOW2_ONHELP = DISPID_EVPROP_ONHELP;
		public const int DISPID_IHTMLWINDOW2_ONERROR = DISPID_EVPROP_ONERROR;
		public const int DISPID_IHTMLWINDOW2_ONRESIZE = DISPID_EVPROP_ONRESIZE;
		public const int DISPID_IHTMLWINDOW2_ONSCROLL = DISPID_EVPROP_ONSCROLL;
		public const int DISPID_IHTMLWINDOW2_DOCUMENT = 1151;
		public const int DISPID_IHTMLWINDOW2_EVENT = 1152;
		public const int DISPID_IHTMLWINDOW2__NEWENUM = 1153;
		public const int DISPID_IHTMLWINDOW2_SHOWMODALDIALOG = 1154;
		public const int DISPID_IHTMLWINDOW2_SHOWHELP = 1155;
		public const int DISPID_IHTMLWINDOW2_SCREEN = 1156;
		public const int DISPID_IHTMLWINDOW2_OPTION = 1157;
		public const int DISPID_IHTMLWINDOW2_FOCUS = 1158;
		public const int DISPID_IHTMLWINDOW2_CLOSED = 23;
		public const int DISPID_IHTMLWINDOW2_BLUR = 1159;
		public const int DISPID_IHTMLWINDOW2_SCROLL = 1160;
		public const int DISPID_IHTMLWINDOW2_CLIENTINFORMATION = 1161;
		public const int DISPID_IHTMLWINDOW2_SETINTERVAL = 1173;
		public const int DISPID_IHTMLWINDOW2_CLEARINTERVAL = 1163;
		public const int DISPID_IHTMLWINDOW2_OFFSCREENBUFFERING = 1164;
		public const int DISPID_IHTMLWINDOW2_EXECSCRIPT = 1165;
		public const int DISPID_IHTMLWINDOW2_TOSTRING = 1166;
		public const int DISPID_IHTMLWINDOW2_SCROLLBY = 1167;
		public const int DISPID_IHTMLWINDOW2_SCROLLTO = 1168;
		public const int DISPID_IHTMLWINDOW2_MOVETO = 6;
		public const int DISPID_IHTMLWINDOW2_MOVEBY = 7;
		public const int DISPID_IHTMLWINDOW2_RESIZETO = 9;
		public const int DISPID_IHTMLWINDOW2_RESIZEBY = 8;
		public const int DISPID_IHTMLWINDOW2_EXTERNAL = 1169;


		//    DISPIDs for interface IHTMLEventObj

		public const int DISPID_EVENTOBJ = 1000;

		public const int DISPID_IHTMLEVENTOBJ_SRCELEMENT = DISPID_EVENTOBJ + 1;
		public const int DISPID_IHTMLEVENTOBJ_ALTKEY = DISPID_EVENTOBJ + 2;
		public const int DISPID_IHTMLEVENTOBJ_CTRLKEY = DISPID_EVENTOBJ + 3;
		public const int DISPID_IHTMLEVENTOBJ_SHIFTKEY = DISPID_EVENTOBJ + 4;
		public const int DISPID_IHTMLEVENTOBJ_RETURNVALUE = DISPID_EVENTOBJ + 7;
		public const int DISPID_IHTMLEVENTOBJ_CANCELBUBBLE = DISPID_EVENTOBJ + 8;
		public const int DISPID_IHTMLEVENTOBJ_FROMELEMENT = DISPID_EVENTOBJ + 9;
		public const int DISPID_IHTMLEVENTOBJ_TOELEMENT = DISPID_EVENTOBJ + 10;
		public const int DISPID_IHTMLEVENTOBJ_KEYCODE = DISPID_EVENTOBJ + 11;
		public const int DISPID_IHTMLEVENTOBJ_BUTTON = DISPID_EVENTOBJ + 12;
		public const int DISPID_IHTMLEVENTOBJ_TYPE = DISPID_EVENTOBJ + 13;
		public const int DISPID_IHTMLEVENTOBJ_QUALIFIER = DISPID_EVENTOBJ + 14;
		public const int DISPID_IHTMLEVENTOBJ_REASON = DISPID_EVENTOBJ + 15;
		public const int DISPID_IHTMLEVENTOBJ_X = DISPID_EVENTOBJ + 5;
		public const int DISPID_IHTMLEVENTOBJ_Y = DISPID_EVENTOBJ + 6;
		public const int DISPID_IHTMLEVENTOBJ_CLIENTX = DISPID_EVENTOBJ + 20;
		public const int DISPID_IHTMLEVENTOBJ_CLIENTY = DISPID_EVENTOBJ + 21;
		public const int DISPID_IHTMLEVENTOBJ_OFFSETX = DISPID_EVENTOBJ + 22;
		public const int DISPID_IHTMLEVENTOBJ_OFFSETY = DISPID_EVENTOBJ + 23;
		public const int DISPID_IHTMLEVENTOBJ_SCREENX = DISPID_EVENTOBJ + 24;
		public const int DISPID_IHTMLEVENTOBJ_SCREENY = DISPID_EVENTOBJ + 25;
		public const int DISPID_IHTMLEVENTOBJ_SRCFILTER = DISPID_EVENTOBJ + 26;

	}
}
