// Autogenerated file!
// Any changes you apply to revision number part will be overwritten next time the tool runs!
// Changes to the major, minor and revision number will be preserved.
// Build Number is autogenerated as: 1 digit current year and 3 digits day of current year.
// Revision Number is SVN revision.

using System.Reflection;
using System.Resources;

[assembly: AssemblyVersion("1.1.3271.1133")]
[assembly: AssemblyFileVersion("1.1.3271.1133")]
[assembly: AssemblyInformationalVersion("1.1.3271")]
[assembly: SatelliteContractVersion("1.1.0")]
