//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Martin Granell, Readify
// 
//      It contains classes defined from the contents of the resource file:
//        C:\Documents and Settings\dareo\My Documents\Visual Studio Projects\RSS Bandit [SVN]\NewsComponents\Resources\ComponentsText.srt.resx
// 
//      Generated: Thursday, August 02, 2007 6:19 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace NewsComponents.Resources
{
    
    
    internal partial class ComponentsText
    {
        
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return Keys_ComponentsText.Culture;
            }
            set
            {
                Keys_ComponentsText.Culture = value;
            }
        }
        
        internal static string ExceptionHelpFeedDesc
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionHelpFeedDesc);
            }
        }
        
        internal static string ExceptionHelpFeedTitle
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionHelpFeedTitle);
            }
        }
        
        internal static string ExceptionResourceAuthorization
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionResourceAuthorization);
            }
        }
        
        internal static string ExceptionResourceGone
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionResourceGone);
            }
        }
        
        internal static string ExceptionSearchFatal
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionSearchFatal);
            }
        }
        
        internal static string ExceptionSearchNoSearchCriteria
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionSearchNoSearchCriteria);
            }
        }
        
        internal static string ExceptionSearchQueryBuilder
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionSearchQueryBuilder);
            }
        }
        
        internal static string ExceptionUnknownXmlDialect
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionUnknownXmlDialect);
            }
        }
        
        internal static string ExceptionUnsupportedAtomVersion
        {
            get
            {
                return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionUnsupportedAtomVersion);
            }
        }
        
        internal static string ExceptionDirectoryNotExistsMessage(string directoryName)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionDirectoryNotExistsMessage, new object[] {
                        directoryName});
        }
        
        internal static string ExceptionEnclosureCacheLimitReached(string fileName, int sizeLimit)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionEnclosureCacheLimitReached, new object[] {
                        fileName,
                        sizeLimit});
        }
        
        internal static string ExceptionHelpFeedItemTitle(string typeOfError)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionHelpFeedItemTitle, new object[] {
                        typeOfError});
        }
        
        internal static string ExceptionLuceneSearchKindNotSupported(string typeOfSearch)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionLuceneSearchKindNotSupported, new object[] {
                        typeOfSearch});
        }
        
        internal static string ExceptionNntpServerAuthenticationFailed(string nntpServer)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionNntpServerAuthenticationFailed, new object[] {
                        nntpServer});
        }
        
        internal static string ExceptionNoProcessingHandlerMessage(string url)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionNoProcessingHandlerMessage, new object[] {
                        url});
        }
        
        internal static string ExceptionRFC2822InvalidTimezoneFormatMessage(string originalDateTimeString)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionRFC2822InvalidTimezoneFormatMessage, new object[] {
                        originalDateTimeString});
        }
        
        internal static string ExceptionRFC2822ParseGroupsMessage(string exceptionTypeName)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionRFC2822ParseGroupsMessage, new object[] {
                        exceptionTypeName});
        }
        
        internal static string ExceptionSearchQueryBuilderFatal(string error)
        {
            return Keys_ComponentsText.GetString(Keys_ComponentsText.ExceptionSearchQueryBuilderFatal, new object[] {
                        error});
        }
        
        internal class Keys_ComponentsText
        {
            
            internal static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("NewsComponents.Resources.ComponentsText.srt", typeof(NewsComponents.Resources.ComponentsText).Assembly);
            
            static System.Globalization.CultureInfo _culture = null;
            
            internal const string ExceptionDirectoryNotExistsMessage = "ExceptionDirectoryNotExistsMessage";
            
            internal const string ExceptionEnclosureCacheLimitReached = "ExceptionEnclosureCacheLimitReached";
            
            internal const string ExceptionHelpFeedDesc = "ExceptionHelpFeedDesc";
            
            internal const string ExceptionHelpFeedItemTitle = "ExceptionHelpFeedItemTitle";
            
            internal const string ExceptionHelpFeedTitle = "ExceptionHelpFeedTitle";
            
            internal const string ExceptionLuceneSearchKindNotSupported = "ExceptionLuceneSearchKindNotSupported";
            
            internal const string ExceptionNntpServerAuthenticationFailed = "ExceptionNntpServerAuthenticationFailed";
            
            internal const string ExceptionNoProcessingHandlerMessage = "ExceptionNoProcessingHandlerMessage";
            
            internal const string ExceptionResourceAuthorization = "ExceptionResourceAuthorization";
            
            internal const string ExceptionResourceGone = "ExceptionResourceGone";
            
            internal const string ExceptionRFC2822InvalidTimezoneFormatMessage = "ExceptionRFC2822InvalidTimezoneFormatMessage";
            
            internal const string ExceptionRFC2822ParseGroupsMessage = "ExceptionRFC2822ParseGroupsMessage";
            
            internal const string ExceptionSearchFatal = "ExceptionSearchFatal";
            
            internal const string ExceptionSearchNoSearchCriteria = "ExceptionSearchNoSearchCriteria";
            
            internal const string ExceptionSearchQueryBuilder = "ExceptionSearchQueryBuilder";
            
            internal const string ExceptionSearchQueryBuilderFatal = "ExceptionSearchQueryBuilderFatal";
            
            internal const string ExceptionUnknownXmlDialect = "ExceptionUnknownXmlDialect";
            
            internal const string ExceptionUnsupportedAtomVersion = "ExceptionUnsupportedAtomVersion";
            
            internal static System.Globalization.CultureInfo Culture
            {
                get
                {
                    return _culture;
                }
                set
                {
                    _culture = value;
                }
            }
            
            internal static string GetString(string key)
            {
                return resourceManager.GetString(key, _culture);
            }
            
            internal static string GetString(string key, object[] args)
            {
                string msg = resourceManager.GetString(key, _culture);
                msg = string.Format(msg, args);
                return msg;
            }
        }
    }
}
