version: 2
updates:
- package-ecosystem: nuget
  directory: "/source"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Lucene.Net.Contrib
    versions:
    - "> 2.9.4.1"
