//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.7.0.833")]
[assembly: AssemblyFileVersion("1.7.0.833")]
[assembly: AssemblyInformationalVersion("1.7.833")]
[assembly: SatelliteContractVersion("1.7.0")]


