//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Resources;

[assembly: AssemblyVersion("1.9.0.1122")]
[assembly: AssemblyFileVersion("1.9.0.1122")]
[assembly: AssemblyInformationalVersion("1.9.1122")]
[assembly: SatelliteContractVersion("1.9.0")]


