//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace RssBandit.Utility.Keyboard {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.25hoursaday.com/2003/RSSBandit/shortcuts/")]
    [System.Xml.Serialization.XmlRootAttribute("shortcuts", Namespace="http://www.25hoursaday.com/2003/RSSBandit/shortcuts/", IsNullable=false)]
    public class ShortcutSettings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shortcut")]
        public ShortcutSetting[] shortcut;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.25hoursaday.com/2003/RSSBandit/shortcuts/")]
    public class ShortcutSetting {
        
        /// <remarks/>
        public string commandName;
        
        /// <remarks/>
        public Shortcut keys;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool display = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.25hoursaday.com/2003/RSSBandit/shortcuts/")]
    public enum Shortcut {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        CtrlA,
        
        /// <remarks/>
        CtrlB,
        
        /// <remarks/>
        CtrlC,
        
        /// <remarks/>
        CtrlD,
        
        /// <remarks/>
        CtrlE,
        
        /// <remarks/>
        CtrlF,
        
        /// <remarks/>
        CtrlG,
        
        /// <remarks/>
        CtrlH,
        
        /// <remarks/>
        CtrlI,
        
        /// <remarks/>
        CtrlJ,
        
        /// <remarks/>
        CtrlK,
        
        /// <remarks/>
        CtrlL,
        
        /// <remarks/>
        CtrlM,
        
        /// <remarks/>
        CtrlN,
        
        /// <remarks/>
        CtrlO,
        
        /// <remarks/>
        CtrlP,
        
        /// <remarks/>
        CtrlQ,
        
        /// <remarks/>
        CtrlR,
        
        /// <remarks/>
        CtrlS,
        
        /// <remarks/>
        CtrlT,
        
        /// <remarks/>
        CtrlU,
        
        /// <remarks/>
        CtrlV,
        
        /// <remarks/>
        CtrlW,
        
        /// <remarks/>
        CtrlX,
        
        /// <remarks/>
        CtrlY,
        
        /// <remarks/>
        CtrlZ,
        
        /// <remarks/>
        CtrlShiftA,
        
        /// <remarks/>
        CtrlShiftB,
        
        /// <remarks/>
        CtrlShiftC,
        
        /// <remarks/>
        CtrlShiftD,
        
        /// <remarks/>
        CtrlShiftE,
        
        /// <remarks/>
        CtrlShiftF,
        
        /// <remarks/>
        CtrlShiftG,
        
        /// <remarks/>
        CtrlShiftH,
        
        /// <remarks/>
        CtrlShiftI,
        
        /// <remarks/>
        CtrlShiftJ,
        
        /// <remarks/>
        CtrlShiftK,
        
        /// <remarks/>
        CtrlShiftL,
        
        /// <remarks/>
        CtrlShiftM,
        
        /// <remarks/>
        CtrlShiftN,
        
        /// <remarks/>
        CtrlShiftO,
        
        /// <remarks/>
        CtrlShiftP,
        
        /// <remarks/>
        CtrlShiftQ,
        
        /// <remarks/>
        CtrlShiftR,
        
        /// <remarks/>
        CtrlShiftS,
        
        /// <remarks/>
        CtrlShiftT,
        
        /// <remarks/>
        CtrlShiftU,
        
        /// <remarks/>
        CtrlShiftV,
        
        /// <remarks/>
        CtrlShiftW,
        
        /// <remarks/>
        CtrlShiftX,
        
        /// <remarks/>
        CtrlShiftY,
        
        /// <remarks/>
        CtrlShiftZ,
        
        /// <remarks/>
        F1,
        
        /// <remarks/>
        F2,
        
        /// <remarks/>
        F3,
        
        /// <remarks/>
        F4,
        
        /// <remarks/>
        F5,
        
        /// <remarks/>
        F6,
        
        /// <remarks/>
        F7,
        
        /// <remarks/>
        F8,
        
        /// <remarks/>
        F9,
        
        /// <remarks/>
        F10,
        
        /// <remarks/>
        F11,
        
        /// <remarks/>
        F12,
        
        /// <remarks/>
        ShiftF1,
        
        /// <remarks/>
        ShiftF2,
        
        /// <remarks/>
        ShiftF3,
        
        /// <remarks/>
        ShiftF4,
        
        /// <remarks/>
        ShiftF5,
        
        /// <remarks/>
        ShiftF6,
        
        /// <remarks/>
        ShiftF7,
        
        /// <remarks/>
        ShiftF8,
        
        /// <remarks/>
        ShiftF9,
        
        /// <remarks/>
        ShiftF10,
        
        /// <remarks/>
        ShiftF11,
        
        /// <remarks/>
        ShiftF12,
        
        /// <remarks/>
        CtrlF1,
        
        /// <remarks/>
        CtrlF2,
        
        /// <remarks/>
        CtrlF3,
        
        /// <remarks/>
        CtrlF4,
        
        /// <remarks/>
        CtrlF5,
        
        /// <remarks/>
        CtrlF6,
        
        /// <remarks/>
        CtrlF7,
        
        /// <remarks/>
        CtrlF8,
        
        /// <remarks/>
        CtrlF9,
        
        /// <remarks/>
        CtrlF10,
        
        /// <remarks/>
        CtrlF11,
        
        /// <remarks/>
        CtrlF12,
        
        /// <remarks/>
        CtrlShiftF1,
        
        /// <remarks/>
        CtrlShiftF2,
        
        /// <remarks/>
        CtrlShiftF3,
        
        /// <remarks/>
        CtrlShiftF4,
        
        /// <remarks/>
        CtrlShiftF5,
        
        /// <remarks/>
        CtrlShiftF6,
        
        /// <remarks/>
        CtrlShiftF7,
        
        /// <remarks/>
        CtrlShiftF8,
        
        /// <remarks/>
        CtrlShiftF9,
        
        /// <remarks/>
        CtrlShiftF10,
        
        /// <remarks/>
        CtrlShiftF11,
        
        /// <remarks/>
        CtrlShiftF12,
        
        /// <remarks/>
        Ins,
        
        /// <remarks/>
        CtrlIns,
        
        /// <remarks/>
        ShiftIns,
        
        /// <remarks/>
        Del,
        
        /// <remarks/>
        CtrlDel,
        
        /// <remarks/>
        ShiftDel,
        
        /// <remarks/>
        AltBksp,
        
        /// <remarks/>
        AltF1,
        
        /// <remarks/>
        AltF2,
        
        /// <remarks/>
        AltF3,
        
        /// <remarks/>
        AltF4,
        
        /// <remarks/>
        AltF5,
        
        /// <remarks/>
        AltF6,
        
        /// <remarks/>
        AltF7,
        
        /// <remarks/>
        AltF8,
        
        /// <remarks/>
        AltF9,
        
        /// <remarks/>
        AltF10,
        
        /// <remarks/>
        AltF11,
        
        /// <remarks/>
        AltF12,
        
        /// <remarks/>
        Alt0,
        
        /// <remarks/>
        Alt1,
        
        /// <remarks/>
        Alt2,
        
        /// <remarks/>
        Alt3,
        
        /// <remarks/>
        Alt4,
        
        /// <remarks/>
        Alt5,
        
        /// <remarks/>
        Alt6,
        
        /// <remarks/>
        Alt7,
        
        /// <remarks/>
        Alt8,
        
        /// <remarks/>
        Alt9,
        
        /// <remarks/>
        Ctrl0,
        
        /// <remarks/>
        Ctrl1,
        
        /// <remarks/>
        Ctrl2,
        
        /// <remarks/>
        Ctrl3,
        
        /// <remarks/>
        Ctrl4,
        
        /// <remarks/>
        Ctrl5,
        
        /// <remarks/>
        Ctrl6,
        
        /// <remarks/>
        Ctrl7,
        
        /// <remarks/>
        Ctrl8,
        
        /// <remarks/>
        Ctrl9,
        
        /// <remarks/>
        CtrlShift0,
        
        /// <remarks/>
        CtrlShift1,
        
        /// <remarks/>
        CtrlShift2,
        
        /// <remarks/>
        CtrlShift3,
        
        /// <remarks/>
        CtrlShift4,
        
        /// <remarks/>
        CtrlShift5,
        
        /// <remarks/>
        CtrlShift6,
        
        /// <remarks/>
        CtrlShift7,
        
        /// <remarks/>
        CtrlShift8,
        
        /// <remarks/>
        CtrlShift9,
    }
}
