//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Resources;

[assembly: AssemblyVersion("1.8.0.894")]
[assembly: AssemblyFileVersion("1.8.0.894")]
[assembly: AssemblyInformationalVersion("1.8.894")]
[assembly: SatelliteContractVersion("1.8.0")]


