//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssBandit.WinGui.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RssBandit.WinGui.Dialogs.DR", typeof(DR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        internal static string ComboMaxItemAge_Item {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item1 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 months.
        /// </summary>
        internal static string ComboMaxItemAge_Item10 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 quarter.
        /// </summary>
        internal static string ComboMaxItemAge_Item11 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 quarters.
        /// </summary>
        internal static string ComboMaxItemAge_Item12 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 quarters.
        /// </summary>
        internal static string ComboMaxItemAge_Item13 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        internal static string ComboMaxItemAge_Item14 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string ComboMaxItemAge_Item15 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item2 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item3 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item4 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item5 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item6 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item7 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 days.
        /// </summary>
        internal static string ComboMaxItemAge_Item8 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month.
        /// </summary>
        internal static string ComboMaxItemAge_Item9 {
            get {
                return ResourceManager.GetString("ComboMaxItemAge_Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogBase_CancelButtonCaption {
            get {
                return ResourceManager.GetString("DialogBase_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss any changes and close.
        /// </summary>
        internal static string DialogBase_CancelButtonCaptionTip {
            get {
                return ResourceManager.GetString("DialogBase_CancelButtonCaptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogBase_SubmitButtonCaption {
            get {
                return ResourceManager.GetString("DialogBase_SubmitButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept all changes and close.
        /// </summary>
        internal static string DialogBase_SubmitButtonCaptionTip {
            get {
                return ResourceManager.GetString("DialogBase_SubmitButtonCaptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option requires higher user privileges (Administrator)....
        /// </summary>
        internal static string DialogBase_UACShieldedHint {
            get {
                return ResourceManager.GetString("DialogBase_UACShieldedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string ExportFeedsDialog_btnOK_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Now export....
        /// </summary>
        internal static string ExportFeedsDialog_btnOK_Tip {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_btnOK_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include item &amp;read states.
        /// </summary>
        internal static string ExportFeedsDialog_checkFormatNativeFull_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_checkFormatNativeFull_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include empty &amp;categories.
        /// </summary>
        internal static string ExportFeedsDialog_checkFormatOPMLIncludeCats_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_checkFormatOPMLIncludeCats_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Feed Source.
        /// </summary>
        internal static string ExportFeedsDialog_grpFromFeedSource_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_grpFromFeedSource_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the feed(s) to &amp;export:.
        /// </summary>
        internal static string ExportFeedsDialog_labelForCheckedTree_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_labelForCheckedTree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string ExportFeedsDialog_labelFormats_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_labelFormats_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Native.
        /// </summary>
        internal static string ExportFeedsDialog_radioFormatNative_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_radioFormatNative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format used by this application internally.
        /// </summary>
        internal static string ExportFeedsDialog_radioFormatNative_Tip {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_radioFormatNative_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OPML.
        /// </summary>
        internal static string ExportFeedsDialog_radioFormatOPML_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_radioFormatOPML_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Outline Processor Markup Language) Format.
        /// </summary>
        internal static string ExportFeedsDialog_radioFormatOPML_Tip {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_radioFormatOPML_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Feeds.
        /// </summary>
        internal static string ExportFeedsDialog_Text {
            get {
                return ResourceManager.GetString("ExportFeedsDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an assigned client certificate....
        /// </summary>
        internal static string FeedProperties_btnRemoveClientCertificate_Tooltip {
            get {
                return ResourceManager.GetString("FeedProperties_btnRemoveClientCertificate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client certificate....
        /// </summary>
        internal static string FeedProperties_btnSelectClientCertificate_Tooltip {
            get {
                return ResourceManager.GetString("FeedProperties_btnSelectClientCertificate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the assigned client certificate....
        /// </summary>
        internal static string FeedProperties_btnViewClientCertificate_Tooltip {
            get {
                return ResourceManager.GetString("FeedProperties_btnViewClientCertificate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a &amp;custom formatter.
        /// </summary>
        internal static string FeedProperties_checkCustomFormatter_Text {
            get {
                return ResourceManager.GetString("FeedProperties_checkCustomFormatter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option to use a custom formatter.
        /// </summary>
        internal static string FeedProperties_checkCustomFormatter_ToolTip {
            get {
                return ResourceManager.GetString("FeedProperties_checkCustomFormatter_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download attachments and podcasts.
        /// </summary>
        internal static string FeedProperties_checkDownloadEnclosures_Text {
            get {
                return ResourceManager.GetString("FeedProperties_checkDownloadEnclosures_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable alert windows for new items.
        /// </summary>
        internal static string FeedProperties_checkEnableAlerts_Text {
            get {
                return ResourceManager.GetString("FeedProperties_checkEnableAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable alert windows for newly downloaded attachments and podcasts.
        /// </summary>
        internal static string FeedProperties_checkEnableEnclosureAlerts_Text {
            get {
                return ResourceManager.GetString("FeedProperties_checkEnableEnclosureAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Mark items as read on exiting feed.
        /// </summary>
        internal static string FeedProperties_checkMarkItemsReadOnExit_Text {
            get {
                return ResourceManager.GetString("FeedProperties_checkMarkItemsReadOnExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set or choose a limit in minutes this feed should be checked for new items again.
        /// </summary>
        internal static string FeedProperties_comboBox1_ToolTip {
            get {
                return ResourceManager.GetString("FeedProperties_comboBox1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a formatter stylesheet.
        /// </summary>
        internal static string FeedProperties_comboFormatters_ToolTip {
            get {
                return ResourceManager.GetString("FeedProperties_comboFormatters_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the maximum item age to keep an item cached.
        /// </summary>
        internal static string FeedProperties_comboMaxItemAge_ToolTip {
            get {
                return ResourceManager.GetString("FeedProperties_comboMaxItemAge_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Title.
        /// </summary>
        internal static string FeedProperties_label1_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Items Older Than:.
        /// </summary>
        internal static string FeedProperties_label15_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label15_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Url.
        /// </summary>
        internal static string FeedProperties_label2_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string FeedProperties_label3_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp;frequency:.
        /// </summary>
        internal static string FeedProperties_label4_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Category.
        /// </summary>
        internal static string FeedProperties_label5_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&amp;name.
        /// </summary>
        internal static string FeedProperties_label6_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password.
        /// </summary>
        internal static string FeedProperties_label7_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label7_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default item formatting or select a custom XSLT formatter..
        /// </summary>
        internal static string FeedProperties_label9_Text {
            get {
                return ResourceManager.GetString("FeedProperties_label9_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Certificate.
        /// </summary>
        internal static string FeedProperties_labelClientCertificate_Text {
            get {
                return ResourceManager.GetString("FeedProperties_labelClientCertificate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter &amp;Stylesheet:.
        /// </summary>
        internal static string FeedProperties_labelFormatters_Text {
            get {
                return ResourceManager.GetString("FeedProperties_labelFormatters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments/Podcasts.
        /// </summary>
        internal static string FeedProperties_tabAttachments_Text {
            get {
                return ResourceManager.GetString("FeedProperties_tabAttachments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string FeedProperties_tabAuthentication_Text {
            get {
                return ResourceManager.GetString("FeedProperties_tabAuthentication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string FeedProperties_tabDisplay_Text {
            get {
                return ResourceManager.GetString("FeedProperties_tabDisplay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Control.
        /// </summary>
        internal static string FeedProperties_tabItemControl_Text {
            get {
                return ResourceManager.GetString("FeedProperties_tabItemControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Properties.
        /// </summary>
        internal static string FeedProperties_Text {
            get {
                return ResourceManager.GetString("FeedProperties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string FeedSourceProperties_groupCredentials_Text {
            get {
                return ResourceManager.GetString("FeedSourceProperties_groupCredentials_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Source Name:.
        /// </summary>
        internal static string FeedSourceProperties_labelFeedSourceName_Text {
            get {
                return ResourceManager.GetString("FeedSourceProperties_labelFeedSourceName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string FeedSourceProperties_labelPassword_Text {
            get {
                return ResourceManager.GetString("FeedSourceProperties_labelPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string FeedSourceProperties_labelUsername_Text {
            get {
                return ResourceManager.GetString("FeedSourceProperties_labelUsername_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Source Properties.
        /// </summary>
        internal static string FeedSourceProperties_Title {
            get {
                return ResourceManager.GetString("FeedSourceProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder:.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFiles2FolderOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFiles2FolderOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes playlist.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFiles2iTunesOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFiles2iTunesOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player playlist.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFiles2WMPOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFiles2WMPOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After downloading copy the podcast to:.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFilesLabelCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFilesLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the destination folder of podcasts.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFilesLocationBrowseTip {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFilesLocationBrowseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder of podcasts.
        /// </summary>
        internal static string PodcastOptionDialog_CopyPodcastFilesLocationTip {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_CopyPodcastFilesLocationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string PodcastOptionDialog_GeneralSectionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_GeneralSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the name of the playlist.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistCustomNameTip {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistCustomNameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all files to a single playlist with this name:.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistFromCustomNameOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistFromCustomNameOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Feed name.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistFromFeedOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistFromFeedOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the file&apos;s source name.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistFromFileSourceOptionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistFromFileSourceOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistSectionCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As playlist name:.
        /// </summary>
        internal static string PodcastOptionDialog_PlaylistSectionLabelCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_PlaylistSectionLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Options.
        /// </summary>
        internal static string PodcastOptionDialog_Title {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat these file types as podcasts - use semicolons (&apos;;&apos;) to separate entries:.
        /// </summary>
        internal static string PodcastOptionDialog_TreatFileTypesCaption {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_TreatFileTypesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of podcast file extensions separated by semicolons.
        /// </summary>
        internal static string PodcastOptionDialog_TreatFileTypesTip {
            get {
                return ResourceManager.GetString("PodcastOptionDialog_TreatFileTypesTip", resourceCulture);
            }
        }
    }
}
