//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsComponents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComponentsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComponentsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsComponents.Resources.ComponentsText", typeof(ComponentsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Facebook User.
        /// </summary>
        internal static string DefaultFacebookCommenterName {
            get {
                return ResourceManager.GetString("DefaultFacebookCommenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access forbidden, client certificate required or invalid.
        /// </summary>
        internal static string ExceptionClientCertificateRequired {
            get {
                return ResourceManager.GetString("ExceptionClientCertificateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Existent Directory: {0}.
        /// </summary>
        internal static string ExceptionDirectoryNotExistsMessage {
            get {
                return ResourceManager.GetString("ExceptionDirectoryNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured downloading the enclosure:
        ///
        ///{0}.
        /// </summary>
        internal static string ExceptionDownloadingEnclosure {
            get {
                return ResourceManager.GetString("ExceptionDownloadingEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to download the file &apos;{0}&apos; failed because it would exceed the size limit of {1}MB dedicated to podcasts and attachments. Either increase the size limit or delete previously downloaded attachments to make room for this download..
        /// </summary>
        internal static string ExceptionEnclosureCacheLimitReached {
            get {
                return ResourceManager.GetString("ExceptionEnclosureCacheLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Facebook subscriptions file has been tampered with and cannot be loaded. Delete Facebook as a feed source and add it again from &quot;Synchronize Feeds&quot; to fix this problem..
        /// </summary>
        internal static string ExceptionFacebookFeedlistCorrupted {
            get {
                return ResourceManager.GetString("ExceptionFacebookFeedlistCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides help on errors.
        /// </summary>
        internal static string ExceptionHelpFeedDesc {
            get {
                return ResourceManager.GetString("ExceptionHelpFeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of error: {0}.
        /// </summary>
        internal static string ExceptionHelpFeedItemTitle {
            get {
                return ResourceManager.GetString("ExceptionHelpFeedItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help on errors.
        /// </summary>
        internal static string ExceptionHelpFeedTitle {
            get {
                return ResourceManager.GetString("ExceptionHelpFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This kind of search is not anymore supported (&apos;{0}&apos;)..
        /// </summary>
        internal static string ExceptionLuceneSearchKindNotSupported {
            get {
                return ResourceManager.GetString("ExceptionLuceneSearchKindNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access, credentials required or invalid credentials (NNTP status 480).
        /// </summary>
        internal static string ExceptionNntpResourceAuthorization {
            get {
                return ResourceManager.GetString("ExceptionNntpResourceAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to NNTP server &apos;{0}&apos; with authentication failed: invalid username/password.
        /// </summary>
        internal static string ExceptionNntpServerAuthenticationFailed {
            get {
                return ResourceManager.GetString("ExceptionNntpServerAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Url &apos;{0}&apos; cannot be processed. No handler implemented..
        /// </summary>
        internal static string ExceptionNoProcessingHandlerMessage {
            get {
                return ResourceManager.GetString("ExceptionNoProcessingHandlerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access, credentials required or invalid credentials (HTTP status 401).
        /// </summary>
        internal static string ExceptionResourceAuthorization {
            get {
                return ResourceManager.GetString("ExceptionResourceAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is not longer available (HTTP status 410).
        /// </summary>
        internal static string ExceptionResourceGone {
            get {
                return ResourceManager.GetString("ExceptionResourceGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Timezone Format: {0}..
        /// </summary>
        internal static string ExceptionRFC2822InvalidTimezoneFormatMessage {
            get {
                return ResourceManager.GetString("ExceptionRFC2822InvalidTimezoneFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC2822 date regex match succeeds, but parse the groups raises a &apos;{0}&apos; exception..
        /// </summary>
        internal static string ExceptionRFC2822ParseGroupsMessage {
            get {
                return ResourceManager.GetString("ExceptionRFC2822ParseGroupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal search error.
        /// </summary>
        internal static string ExceptionSearchFatal {
            get {
                return ResourceManager.GetString("ExceptionSearchFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search criteria specified.
        /// </summary>
        internal static string ExceptionSearchNoSearchCriteria {
            get {
                return ResourceManager.GetString("ExceptionSearchNoSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query could not be build from search criterias.
        /// </summary>
        internal static string ExceptionSearchQueryBuilder {
            get {
                return ResourceManager.GetString("ExceptionSearchQueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query could not be build from search criterias. An error was caused: {0}.
        /// </summary>
        internal static string ExceptionSearchQueryBuilderFatal {
            get {
                return ResourceManager.GetString("ExceptionSearchQueryBuilderFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This XML document does not look like an RSS feed.
        /// </summary>
        internal static string ExceptionUnknownXmlDialect {
            get {
                return ResourceManager.GetString("ExceptionUnknownXmlDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ATOM version.
        /// </summary>
        internal static string ExceptionUnsupportedAtomVersion {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedAtomVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        internal static string FacebookNewsFeedTitle {
            get {
                return ResourceManager.GetString("FacebookNewsFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        internal static string FacebookStyleSheet {
            get {
                return ResourceManager.GetString("FacebookStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User.
        /// </summary>
        internal static string FacebookUnknownUser {
            get {
                return ResourceManager.GetString("FacebookUnknownUser", resourceCulture);
            }
        }
    }
}
