// Autogenerated file!
// Any changes you apply to revision number part will be overwritten next time the tool runs!
// Changes to the major, minor and build number will be preserved.
// Revision Number is autogenerated as: 1 digit current year and 3 digits day of current year.

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("1.1.113.6327")]
